<script lang="tsx" setup>
import { MenuTypeEnum, generateCssVars } from 'vft';
import { recursion } from '@vft/utils';
import LinkStatus from './status.vue';

// eslint-disable max-lines
const headerList = [
  {
    type: MenuTypeEnum.TILE,
    'id': '10',
    'isGroup': 1,
    'name': '绿色金融',
    'functions': [
      {
        'id': '1001',
        'isGroup': 1,
        'defaultFunction': null,
        'name': '绿色信贷',
        'functions': [
          {
            'id': '380',
            'isGroup': 0,
            'defaultFunction': null,
            'name': '绿色信贷',
            'fullName': null,
            'enName': null,
            'icon': null,
            'image': null,
            'url': '/greenCredit/greenCredit',
            'status': 0,
            'nextGroupId': null,
            'type': 'toWeb',
            'label': null,
            'inGroupOrder': 1,
            'parentId': null,
            'count': null,
            'functions': null,
            'functionLabel': null,
            'fid': '102'
          },
          {
            'id': '381',
            'isGroup': 0,
            'defaultFunction': null,
            'name': '碳减排支持工具',
            'fullName': null,
            'enName': null,
            'icon': null,
            'image': null,
            'url': '/greenCredit/carbonReduction',
            'status': 0,
            'nextGroupId': null,
            'type': null,
            'label': null,
            'inGroupOrder': 2,
            'parentId': null,
            'count': null,
            'functions': null,
            'functionLabel': null,
            'fid': '106'
          }
        ],
        'functionLabel': null,
        'fid': null
      },
      {
        'id': '1002',
        'isGroup': 1,
        'defaultFunction': null,
        'name': '绿色保险',

        'functions': [
          {
            'id': '383',
            'isGroup': 0,
            'defaultFunction': null,
            'name': '纳入环责险企业',
            'fullName': '纳入环责险企业',
            'enName': null,
            'icon': null,
            'image': null,
            'url': '/greenInsurance/included',
            'status': 0,
            'nextGroupId': null,
            'type': null,
            'label': null,
            'inGroupOrder': 1,
            'parentId': null,
            'count': null,
            'functions': null,
            'functionLabel': null,
            'fid': '152'
          },
          {
            'id': '384',
            'isGroup': 0,
            'defaultFunction': null,
            'name': '投保环责险企业',
            'fullName': '投保环责险企业',
            'enName': null,
            'icon': null,
            'image': null,
            'url': '/greenInsurance/insured',
            'status': 0,
            'nextGroupId': null,
            'type': null,
            'label': null,
            'inGroupOrder': 2,
            'parentId': null,
            'count': null,
            'functions': null,
            'functionLabel': null,
            'fid': '153'
          },
          {
            'id': '385',
            'isGroup': 0,
            'defaultFunction': null,
            'name': '环责险补贴企业',
            'fullName': '环责险补贴企业',
            'enName': null,
            'icon': null,
            'image': null,
            'url': '/greenInsurance/subsidies',
            'status': 0,
            'nextGroupId': null,
            'type': null,
            'label': null,
            'inGroupOrder': 3,
            'parentId': null,
            'count': null,
            'functions': null,
            'functionLabel': null,
            'fid': '154'
          }
        ],
        'functionLabel': null,
        'fid': null
      },
      {
        'id': '1003',
        'isGroup': 1,
        'defaultFunction': null,
        'name': '绿色债券',

        'functions': [
          {
            'id': '100301',
            'isGroup': 0,
            'defaultFunction': null,
            'name': '绿色债券',
            'fullName': null,
            'enName': null,
            'icon': null,
            'image': null,
            'url': '/greenBond/bondList/1',
            'status': 0,
            'nextGroupId': null,
            'type': null,
            'label': null,
            'inGroupOrder': null,
            'parentId': null,
            'count': null,
            'functions': null,
            'functionLabel': null,
            'fid': null
          },
          {
            'id': '100302',
            'isGroup': 0,
            'defaultFunction': null,
            'name': '绿色债券发行人',
            'fullName': null,
            'enName': null,
            'icon': null,
            'image': null,
            'url': '/greenBond/bondRelease/1',
            'status': 0,
            'nextGroupId': null,
            'type': null,
            'label': null,
            'inGroupOrder': null,
            'parentId': null,
            'count': null,
            'functions': null,
            'functionLabel': null,
            'fid': null
          },
          {
            'id': '388',
            'isGroup': 0,
            'defaultFunction': null,
            'name': '绿债项目',
            'fullName': null,
            'enName': null,
            'icon': null,
            'image': null,
            'url': '/greenBond/bondProject',
            'status': 0,
            'nextGroupId': null,
            'type': null,
            'label': null,
            'inGroupOrder': 3,
            'parentId': null,
            'count': null,
            'functions': null,
            'functionLabel': null,
            'fid': '181'
          },
          {
            'id': '389',
            'isGroup': 0,
            'defaultFunction': null,
            'name': '绿债评估机构',
            'fullName': null,
            'enName': null,
            'icon': null,
            'image': null,
            'url': '/greenBond/bondEvaluate',
            'status': 0,
            'nextGroupId': null,
            'type': null,
            'label': null,
            'inGroupOrder': 4,
            'parentId': null,
            'count': null,
            'functions': null,
            'functionLabel': null,
            'fid': '182'
          }
        ],
        'functionLabel': null,
        'fid': null
      },
      {
        'id': '1004',
        'isGroup': 1,
        'defaultFunction': null,
        'name': '绿色制造',

        'functions': [
          {
            'id': '390',
            'isGroup': 0,
            'defaultFunction': null,
            'name': '绿色工厂',
            'fullName': '绿色工厂',
            'enName': null,
            'icon': 'https://hbt.obs.cn-east-2.myhuaweicloud.com/uat/app_home_config/2022/08/01/b96ef05b5bf840eda954587d88ec7184.png',
            'image': null,
            'url': '/greenManufacturing/greenFactory',
            'status': 0,
            'nextGroupId': null,
            'type': 'toWeb',
            'label': null,
            'inGroupOrder': 1,
            'parentId': null,
            'count': null,
            'functions': null,
            'functionLabel': null,
            'fid': '88'
          },
          {
            'id': '391',
            'isGroup': 0,
            'defaultFunction': null,
            'name': '绿色供应链管理企业',
            'fullName': null,
            'enName': null,
            'icon': null,
            'image': null,
            'url': '/greenManufacturing/greenSupplyChain',
            'status': 0,
            'nextGroupId': null,
            'type': null,
            'label': null,
            'inGroupOrder': 2,
            'parentId': null,
            'count': null,
            'functions': null,
            'functionLabel': null,
            'fid': '184'
          },
          {
            'id': '392',
            'isGroup': 0,
            'defaultFunction': null,
            'name': '绿色工业园区',
            'fullName': null,
            'enName': null,
            'icon': null,
            'image': null,
            'url': null,
            'status': 0,
            'nextGroupId': null,
            'type': null,
            'label': null,
            'inGroupOrder': 3,
            'parentId': null,
            'count': null,
            'functions': null,
            'functionLabel': {
              'id': null,
              'name': '待上线',
              'description': null,
              'color': '#8B8C8C',
              'bgColor': '#F6F6F6'
            },
            'fid': '185'
          },
          {
            'id': '393',
            'isGroup': 0,
            'defaultFunction': null,
            'name': '绿色设计产品名单',
            'fullName': '绿色设计产品名单',
            'enName': null,
            'icon': 'https://hbt.obs.cn-east-2.myhuaweicloud.com/uat/app_home_config/2022/08/01/61e871d592c244539fc9d7e338fa29c4.png',
            'image': null,
            'url': '/greenManufacturing/greenDesignList',
            'status': 0,
            'nextGroupId': null,
            'type': 'toWeb',
            'label': null,
            'inGroupOrder': 4,
            'parentId': null,
            'count': null,
            'functions': null,
            'functionLabel': null,
            'fid': '108'
          },
          {
            'id': '394',
            'isGroup': 0,
            'defaultFunction': null,
            'name': '工业产品绿色设计示范企业',
            'fullName': '工业产品绿色设计示范企业',
            'enName': null,
            'icon': 'https://hbt.obs.cn-east-2.myhuaweicloud.com/uat/app_home_config/2022/08/01/b1348e16ded34a7bacc7b9ed0e08c303.png',
            'image': null,
            'url': '/greenManufacturing/greenDesignModel',
            'status': 0,
            'nextGroupId': null,
            'type': 'toWeb',
            'label': null,
            'inGroupOrder': 5,
            'parentId': null,
            'count': null,
            'functions': null,
            'functionLabel': null,
            'fid': '169'
          }
        ],
        'functionLabel': null,
        'fid': null
      },
      {
        'id': '1005',
        'isGroup': 1,
        'defaultFunction': null,
        'name': '绿色环保认证',

        'functions': [
          {
            'id': '481',
            'isGroup': 0,
            'defaultFunction': null,
            'name': '绿色企业',
            'fullName': '绿色企业',
            'enName': null,
            'icon': 'https://hbt.obs.cn-east-2.myhuaweicloud.com/uat/app_home_config/2022/08/01/bf8f9b1e635d4a458370326aa2d40cfe.png',
            'image': null,
            'url': '/greenCertification/greenCompany',
            'status': 0,
            'nextGroupId': null,
            'type': 'toWeb',
            'label': null,
            'inGroupOrder': 1,
            'parentId': null,
            'count': null,
            'functions': null,
            'functionLabel': null,
            'fid': '89'
          },
          {
            'id': '395',
            'isGroup': 0,
            'defaultFunction': null,
            'name': '绿色矿山',
            'fullName': '绿色矿山',
            'enName': null,
            'icon': 'https://hbt.obs.cn-east-2.myhuaweicloud.com/uat/app_home_config/2022/08/01/61e871d592c244539fc9d7e338fa29c4.png',
            'image': null,
            'url': '/greenCertification/greenMine',
            'status': 0,
            'nextGroupId': null,
            'type': 'toWeb',
            'label': null,
            'inGroupOrder': 2,
            'parentId': null,
            'count': null,
            'functions': null,
            'functionLabel': null,
            'fid': '90'
          },
          {
            'id': '397',
            'isGroup': 0,
            'defaultFunction': null,
            'name': '绿色产品认证',
            'fullName': null,
            'enName': null,
            'icon': null,
            'image': null,
            'url': '/greenCertification/greenProduct',
            'status': 0,
            'nextGroupId': null,
            'type': null,
            'label': null,
            'inGroupOrder': 4,
            'parentId': null,
            'count': null,
            'functions': null,
            'functionLabel': null,
            'fid': '146'
          },
          {
            'id': '399',
            'isGroup': 0,
            'defaultFunction': null,
            'name': '中国III型环境产品声明评价获证企业',
            'fullName': null,
            'enName': null,
            'icon': null,
            'image': null,
            'url': null,
            'status': 0,
            'nextGroupId': null,
            'type': null,
            'label': null,
            'inGroupOrder': 6,
            'parentId': null,
            'count': null,
            'functions': null,
            'functionLabel': {
              'id': null,
              'name': '待上线',
              'description': null,
              'color': '#8B8C8C',
              'bgColor': '#F6F6F6'
            },
            'fid': '192'
          },
          {
            'id': '400',
            'isGroup': 0,
            'defaultFunction': null,
            'name': '中国环保产品II型认证获证企业名录',
            'fullName': null,
            'enName': null,
            'icon': null,
            'image': null,
            'url': null,
            'status': 0,
            'nextGroupId': null,
            'type': null,
            'label': null,
            'inGroupOrder': 7,
            'parentId': null,
            'count': null,
            'functions': null,
            'functionLabel': {
              'id': null,
              'name': '待上线',
              'description': null,
              'color': '#8B8C8C',
              'bgColor': '#F6F6F6'
            },
            'fid': '193'
          }
        ],
        'functionLabel': null,
        'fid': null
      },
      {
        'id': '1006',
        'isGroup': 1,
        'defaultFunction': null,
        'name': '绿色建筑建材',

        'functions': [
          {
            'id': '401',
            'isGroup': 0,
            'defaultFunction': null,
            'name': '绿色建筑评价标识项目',
            'fullName': null,
            'enName': null,
            'icon': null,
            'image': null,
            'url': '/greenMaterials/buildingProject',
            'status': 0,
            'nextGroupId': null,
            'type': null,
            'label': null,
            'inGroupOrder': 1,
            'parentId': null,
            'count': null,
            'functions': null,
            'functionLabel': null,
            'fid': '194'
          },
          {
            'id': '403',
            'isGroup': 0,
            'defaultFunction': null,
            'name': '绿色建材评价证书',
            'fullName': null,
            'enName': null,
            'icon': null,
            'image': null,
            'url': null,
            'status': 0,
            'nextGroupId': null,
            'type': null,
            'label': null,
            'inGroupOrder': 3,
            'parentId': null,
            'count': null,
            'functions': null,
            'functionLabel': {
              'id': null,
              'name': '待上线',
              'description': null,
              'color': '#8B8C8C',
              'bgColor': '#F6F6F6'
            },
            'fid': '196'
          },
          {
            'id': '404',
            'isGroup': 0,
            'defaultFunction': null,
            'name': '绿色建材认证',
            'fullName': null,
            'enName': null,
            'icon': null,
            'image': null,
            'url': null,
            'status': 0,
            'nextGroupId': null,
            'type': null,
            'label': null,
            'inGroupOrder': 4,
            'parentId': null,
            'count': null,
            'functions': null,
            'functionLabel': {
              'id': null,
              'name': '待上线',
              'description': null,
              'color': '#8B8C8C',
              'bgColor': '#F6F6F6'
            },
            'fid': '197'
          }
        ],
        'functionLabel': null,
        'fid': null
      },
      {
        'id': '1007',
        'isGroup': 1,
        'defaultFunction': '405',
        'name': '环保装备及技术',

        'functions': [
          {
            'id': '405',
            'isGroup': 0,
            'defaultFunction': null,
            'name': '环保装备制造规范企业',
            'fullName': null,
            'enName': null,
            'icon': null,
            'image': null,
            'url': '/equipmentTechnology/standard',
            'status': 0,
            'nextGroupId': null,
            'type': null,
            'label': null,
            'inGroupOrder': 1,
            'parentId': null,
            'count': null,
            'functions': null,
            'functionLabel': null,
            'fid': '163'
          },
          {
            'id': '406',
            'isGroup': 0,
            'defaultFunction': null,
            'name': '重大环保技术装备',
            'fullName': null,
            'enName': null,
            'icon': null,
            'image': null,
            'url': '/equipmentTechnology/major',
            'status': 0,
            'nextGroupId': null,
            'type': null,
            'label': null,
            'inGroupOrder': 2,
            'parentId': null,
            'count': null,
            'functions': null,
            'functionLabel': null,
            'fid': '164'
          },
          {
            'id': '407',
            'isGroup': 0,
            'defaultFunction': null,
            'name': '水污染防治技术、产品、服务目录',
            'fullName': null,
            'enName': null,
            'icon': null,
            'image': null,
            'url': '/equipmentTechnology/waterPollution',
            'status': 0,
            'nextGroupId': null,
            'type': null,
            'label': null,
            'inGroupOrder': 3,
            'parentId': null,
            'count': null,
            'functions': null,
            'functionLabel': null,
            'fid': '165'
          }
        ],
        'functionLabel': null,
        'fid': null
      },
      {
        'id': '1008',
        'isGroup': 1,
        'defaultFunction': null,
        'name': '节能节水',

        'functions': [
          {
            'id': '410',
            'isGroup': 0,
            'defaultFunction': null,
            'name': '能效之星产品',
            'fullName': null,
            'enName': null,
            'icon': null,
            'image': null,
            'url': '/energy/product',
            'status': 0,
            'nextGroupId': null,
            'type': null,
            'label': null,
            'inGroupOrder': 3,
            'parentId': null,
            'count': null,
            'functions': null,
            'functionLabel': null,
            'fid': '161'
          },
          {
            'id': '411',
            'isGroup': 0,
            'defaultFunction': null,
            'name': '能效领跑者企业',
            'fullName': null,
            'enName': null,
            'icon': null,
            'image': null,
            'url': '/energy/leader',
            'status': 0,
            'nextGroupId': null,
            'type': null,
            'label': null,
            'inGroupOrder': 4,
            'parentId': null,
            'count': null,
            'functions': null,
            'functionLabel': null,
            'fid': '175'
          },
          {
            'id': '412',
            'isGroup': 0,
            'defaultFunction': null,
            'name': '政府采购节能产品',
            'fullName': null,
            'enName': null,
            'icon': null,
            'image': null,
            'url': null,
            'status': 0,
            'nextGroupId': null,
            'type': null,
            'label': null,
            'inGroupOrder': 5,
            'parentId': null,
            'count': null,
            'functions': null,
            'functionLabel': {
              'id': null,
              'name': '待上线',
              'description': null,
              'color': '#8B8C8C',
              'bgColor': '#F6F6F6'
            },
            'fid': '202'
          },
          {
            'id': '414',
            'isGroup': 0,
            'defaultFunction': null,
            'name': '政府采购节水产品',
            'fullName': null,
            'enName': null,
            'icon': null,
            'image': null,
            'url': null,
            'status': 0,
            'nextGroupId': null,
            'type': null,
            'label': null,
            'inGroupOrder': 7,
            'parentId': null,
            'count': null,
            'functions': null,
            'functionLabel': {
              'id': null,
              'name': '待上线',
              'description': null,
              'color': '#8B8C8C',
              'bgColor': '#F6F6F6'
            },
            'fid': '204'
          },
          {
            'id': '415',
            'isGroup': 0,
            'defaultFunction': null,
            'name': '国家成熟适用节水技术推广',
            'fullName': null,
            'enName': null,
            'icon': null,
            'image': null,
            'url': '/energy/promotion',
            'status': 0,
            'nextGroupId': null,
            'type': null,
            'label': null,
            'inGroupOrder': 8,
            'parentId': null,
            'count': null,
            'functions': null,
            'functionLabel': null,
            'fid': '162'
          }
        ],
        'functionLabel': null,
        'fid': null
      },
      {
        'id': '1009',
        'isGroup': 1,
        'defaultFunction': null,
        'name': '资源综合利用',

        'functions': [
          {
            'id': '416',
            'isGroup': 0,
            'defaultFunction': null,
            'name': '建筑垃圾资源化利用规范企业',
            'fullName': '建筑垃圾资源化利用规范企业',
            'enName': null,
            'icon': null,
            'image': null,
            'url': '/resourceUtilization/constructionWaste',
            'status': 0,
            'nextGroupId': null,
            'type': null,
            'label': null,
            'inGroupOrder': 1,
            'parentId': null,
            'count': null,
            'functions': null,
            'functionLabel': null,
            'fid': '170'
          },
          {
            'id': '417',
            'isGroup': 0,
            'defaultFunction': null,
            'name': '废钢铁加工行业准入企业',
            'fullName': '废钢铁加工行业准入企业',
            'enName': null,
            'icon': null,
            'image': null,
            'url': '/resourceUtilization/scrapIronProcessingIndustry',
            'status': 0,
            'nextGroupId': null,
            'type': null,
            'label': null,
            'inGroupOrder': 2,
            'parentId': null,
            'count': null,
            'functions': null,
            'functionLabel': null,
            'fid': '171'
          },
          {
            'id': '418',
            'isGroup': 0,
            'defaultFunction': null,
            'name': '废塑料综合利用规范企业',
            'fullName': '废塑料综合利用规范企业',
            'enName': null,
            'icon': null,
            'image': null,
            'url': '/resourceUtilization/wastePlastic',
            'status': 0,
            'nextGroupId': null,
            'type': null,
            'label': null,
            'inGroupOrder': 3,
            'parentId': null,
            'count': null,
            'functions': null,
            'functionLabel': null,
            'fid': '172'
          },
          {
            'id': '419',
            'isGroup': 0,
            'defaultFunction': null,
            'name': '废矿物油综合利用规范企业',
            'fullName': '废矿物油综合利用规范企业',
            'enName': null,
            'icon': null,
            'image': null,
            'url': '/resourceUtilization/wasteMineralOil',
            'status': 0,
            'nextGroupId': null,
            'type': null,
            'label': null,
            'inGroupOrder': 4,
            'parentId': null,
            'count': null,
            'functions': null,
            'functionLabel': null,
            'fid': '173'
          },
          {
            'id': '420',
            'isGroup': 0,
            'defaultFunction': null,
            'name': '废弃电子产品回收企业',
            'fullName': null,
            'enName': null,
            'icon': null,
            'image': null,
            'url': '/resourceUtilization/wasteElectronicRecycling',
            'status': 0,
            'nextGroupId': null,
            'type': null,
            'label': null,
            'inGroupOrder': 5,
            'parentId': null,
            'count': null,
            'functions': null,
            'functionLabel': null,
            'fid': '210'
          },
          {
            'id': '421',
            'isGroup': 0,
            'defaultFunction': null,
            'name': '再制造产品制造商',
            'fullName': '再制造产品制造商',
            'enName': null,
            'icon': null,
            'image': null,
            'url': '/resourceUtilization/remanufacturedManufacturer',
            'status': 0,
            'nextGroupId': null,
            'type': null,
            'label': null,
            'inGroupOrder': 6,
            'parentId': null,
            'count': null,
            'functions': null,
            'functionLabel': null,
            'fid': '174'
          }
        ],
        'functionLabel': null,
        'fid': null
      }
    ],
    menuOrder: [[0, 1], [2, 3, 4]]
  },
  {
    type: MenuTypeEnum.TILE,
    'id': '20',
    'isGroup': 1,
    'name': 'ESG',
    showArrow: false,
    'functions': [
      {
        'id': '2001',
        'isGroup': 1,
        'defaultFunction': null,
        'name': 'ESG',

        'functions': [
          {
            'id': '200101',
            'isGroup': 0,
            'defaultFunction': null,
            'name': 'ESG争议事件',
            'fullName': null,
            'enName': null,
            'icon': null,
            'image': null,
            'url': '/esgEvent/event/ag',
            'status': 0,
            'nextGroupId': null,
            'type': null,
            'label': null,
            'inGroupOrder': null,
            'parentId': null,
            'count': null,
            'functions': null,
            'functionLabel': null,
            'fid': null
          },
          {
            'id': '200102',
            'isGroup': 0,
            'defaultFunction': null,
            'name': 'ESG报告',
            'fullName': null,
            'enName': null,
            'icon': null,
            'image': null,
            'url': null,
            'status': 0,
            'nextGroupId': null,
            'type': null,
            'label': null,
            'inGroupOrder': null,
            'parentId': null,
            'count': null,
            'functions': null,
            'functionLabel': null,
            'fid': null
          },
          {
            'id': '200103',
            'isGroup': 0,
            'defaultFunction': null,
            'name': 'ESG获奖',
            'fullName': null,
            'enName': null,
            'icon': null,
            'image': null,
            'url': null,
            'status': 0,
            'nextGroupId': null,
            'type': null,
            'label': null,
            'inGroupOrder': null,
            'parentId': null,
            'count': null,
            'functions': null,
            'functionLabel': null,
            'fid': null
          },
          {
            'id': '200104',
            'isGroup': 0,
            'defaultFunction': null,
            'name': 'ESG动态',
            'fullName': null,
            'enName': null,
            'icon': null,
            'image': null,
            'url': null,
            'status': 0,
            'nextGroupId': null,
            'type': null,
            'label': null,
            'inGroupOrder': null,
            'parentId': null,
            'count': null,
            'functions': null,
            'functionLabel': null,
            'fid': null
          }
        ],
        'functionLabel': null,
        'fid': null
      },
      {
        'id': '2002',
        'isGroup': 1,
        'defaultFunction': null,
        'name': '环境',

        'functions': [
          {
            'id': '549',
            'isGroup': 0,
            'defaultFunction': null,
            'name': '温室气体',
            'fullName': null,
            'enName': null,
            'icon': null,
            'image': null,
            'url': '/esg/environment/ag/10',
            'status': 0,
            'nextGroupId': null,
            'type': null,
            'label': null,
            'inGroupOrder': 1,
            'parentId': null,
            'count': null,
            'functions': null,
            'functionLabel': null,
            'fid': '239'
          },
          {
            'id': '550',
            'isGroup': 0,
            'defaultFunction': null,
            'name': '能源',
            'fullName': null,
            'enName': null,
            'icon': null,
            'image': null,
            'url': '/esg/environment/ag/20',
            'status': 0,
            'nextGroupId': null,
            'type': null,
            'label': null,
            'inGroupOrder': 2,
            'parentId': null,
            'count': null,
            'functions': null,
            'functionLabel': null,
            'fid': '235'
          },
          {
            'id': '551',
            'isGroup': 0,
            'defaultFunction': null,
            'name': '水资源',
            'fullName': null,
            'enName': null,
            'icon': null,
            'image': null,
            'url': '/esg/environment/ag/30',
            'status': 0,
            'nextGroupId': null,
            'type': null,
            'label': null,
            'inGroupOrder': 3,
            'parentId': null,
            'count': null,
            'functions': null,
            'functionLabel': null,
            'fid': '240'
          },
          {
            'id': '552',
            'isGroup': 0,
            'defaultFunction': null,
            'name': '污染物',
            'fullName': null,
            'enName': null,
            'icon': null,
            'image': null,
            'url': '/esg/environment/ag/40',
            'status': 0,
            'nextGroupId': null,
            'type': null,
            'label': null,
            'inGroupOrder': 4,
            'parentId': null,
            'count': null,
            'functions': null,
            'functionLabel': null,
            'fid': '241'
          },
          {
            'id': '553',
            'isGroup': 0,
            'defaultFunction': null,
            'name': '废弃物',
            'fullName': null,
            'enName': null,
            'icon': null,
            'image': null,
            'url': '/esg/environment/ag/50',
            'status': 0,
            'nextGroupId': null,
            'type': null,
            'label': null,
            'inGroupOrder': 5,
            'parentId': null,
            'count': null,
            'functions': null,
            'functionLabel': null,
            'fid': '242'
          },
          {
            'id': '554',
            'isGroup': 0,
            'defaultFunction': null,
            'name': '环保投入',
            'fullName': null,
            'enName': null,
            'icon': null,
            'image': null,
            'url': '/esg/environment/ag/51',
            'status': 0,
            'nextGroupId': null,
            'type': null,
            'label': null,
            'inGroupOrder': 6,
            'parentId': null,
            'count': null,
            'functions': null,
            'functionLabel': null,
            'fid': '243'
          }
        ],
        'functionLabel': null,
        'fid': null
      },
      {
        'id': '2003',
        'isGroup': 1,
        'defaultFunction': null,
        'name': '社会责任',

        'functions': [
          {
            'id': '555',
            'isGroup': 0,
            'defaultFunction': null,
            'name': '人力资源',
            'fullName': null,
            'enName': null,
            'icon': null,
            'image': null,
            'url': '/esg/social/ag/80',
            'status': 0,
            'nextGroupId': null,
            'type': null,
            'label': null,
            'inGroupOrder': 1,
            'parentId': null,
            'count': null,
            'functions': null,
            'functionLabel': null,
            'fid': '244'
          },
          {
            'id': '556',
            'isGroup': 0,
            'defaultFunction': null,
            'name': '薪酬与福利',
            'fullName': null,
            'enName': null,
            'icon': null,
            'image': null,
            'url': '/esg/social/ag/90',
            'status': 0,
            'nextGroupId': null,
            'type': null,
            'label': null,
            'inGroupOrder': 2,
            'parentId': null,
            'count': null,
            'functions': null,
            'functionLabel': null,
            'fid': '245'
          },
          {
            'id': '557',
            'isGroup': 0,
            'defaultFunction': null,
            'name': '培训与发展',
            'fullName': null,
            'enName': null,
            'icon': null,
            'image': null,
            'url': '/esg/social/ag/100',
            'status': 0,
            'nextGroupId': null,
            'type': null,
            'label': null,
            'inGroupOrder': 3,
            'parentId': null,
            'count': null,
            'functions': null,
            'functionLabel': null,
            'fid': '246'
          },
          {
            'id': '558',
            'isGroup': 0,
            'defaultFunction': null,
            'name': '健康与安全',
            'fullName': null,
            'enName': null,
            'icon': null,
            'image': null,
            'url': '/esg/social/ag/110',
            'status': 0,
            'nextGroupId': null,
            'type': null,
            'label': null,
            'inGroupOrder': 4,
            'parentId': null,
            'count': null,
            'functions': null,
            'functionLabel': null,
            'fid': '247'
          },
          {
            'id': '559',
            'isGroup': 0,
            'defaultFunction': null,
            'name': '产品责任',
            'fullName': null,
            'enName': null,
            'icon': null,
            'image': null,
            'url': '/esg/social/ag/120',
            'status': 0,
            'nextGroupId': null,
            'type': null,
            'label': null,
            'inGroupOrder': 5,
            'parentId': null,
            'count': null,
            'functions': null,
            'functionLabel': null,
            'fid': '248'
          },
          {
            'id': '560',
            'isGroup': 0,
            'defaultFunction': null,
            'name': '供应商',
            'fullName': null,
            'enName': null,
            'icon': null,
            'image': null,
            'url': '/esg/social/ag/130',
            'status': 0,
            'nextGroupId': null,
            'type': null,
            'label': null,
            'inGroupOrder': 6,
            'parentId': null,
            'count': null,
            'functions': null,
            'functionLabel': null,
            'fid': '249'
          },
          {
            'id': '561',
            'isGroup': 0,
            'defaultFunction': null,
            'name': '公益与扶贫',
            'fullName': null,
            'enName': null,
            'icon': null,
            'image': null,
            'url': '/esg/social/ag/140',
            'status': 0,
            'nextGroupId': null,
            'type': null,
            'label': null,
            'inGroupOrder': 7,
            'parentId': null,
            'count': null,
            'functions': null,
            'functionLabel': null,
            'fid': '250'
          }
        ],
        'functionLabel': null,
        'fid': null
      },
      {
        'id': '2004',
        'isGroup': 1,
        'defaultFunction': null,
        'name': '公司治理',

        'functions': [
          {
            'id': '562',
            'isGroup': 0,
            'defaultFunction': null,
            'name': '股权与股东',
            'fullName': null,
            'enName': null,
            'icon': null,
            'image': null,
            'url': '/esg/governance/ag/150',
            'status': 0,
            'nextGroupId': null,
            'type': null,
            'label': null,
            'inGroupOrder': 1,
            'parentId': null,
            'count': null,
            'functions': null,
            'functionLabel': null,
            'fid': '251'
          },
          {
            'id': '563',
            'isGroup': 0,
            'defaultFunction': null,
            'name': '董事会',
            'fullName': null,
            'enName': null,
            'icon': null,
            'image': null,
            'url': '/esg/governance/ag/160',
            'status': 0,
            'nextGroupId': null,
            'type': null,
            'label': null,
            'inGroupOrder': 2,
            'parentId': null,
            'count': null,
            'functions': null,
            'functionLabel': null,
            'fid': '252'
          },
          {
            'id': '564',
            'isGroup': 0,
            'defaultFunction': null,
            'name': '监事会',
            'fullName': null,
            'enName': null,
            'icon': null,
            'image': null,
            'url': '/esg/governance/ag/170',
            'status': 0,
            'nextGroupId': null,
            'type': null,
            'label': null,
            'inGroupOrder': 3,
            'parentId': null,
            'count': null,
            'functions': null,
            'functionLabel': null,
            'fid': '253'
          },
          {
            'id': '565',
            'isGroup': 0,
            'defaultFunction': null,
            'name': '高管层',
            'fullName': null,
            'enName': null,
            'icon': null,
            'image': null,
            'url': '/esg/governance/ag/180',
            'status': 0,
            'nextGroupId': null,
            'type': null,
            'label': null,
            'inGroupOrder': 4,
            'parentId': null,
            'count': null,
            'functions': null,
            'functionLabel': null,
            'fid': '254'
          },
          {
            'id': '566',
            'isGroup': 0,
            'defaultFunction': null,
            'name': '信息披露',
            'fullName': null,
            'enName': null,
            'icon': null,
            'image': null,
            'url': '/esg/governance/ag/190',
            'status': 0,
            'nextGroupId': null,
            'type': null,
            'label': null,
            'inGroupOrder': 5,
            'parentId': null,
            'count': null,
            'functions': null,
            'functionLabel': null,
            'fid': '255'
          },
          {
            'id': '567',
            'isGroup': 0,
            'defaultFunction': null,
            'name': '对外担保',
            'fullName': null,
            'enName': null,
            'icon': null,
            'image': null,
            'url': '/esg/governance/ag/200',
            'status': 0,
            'nextGroupId': null,
            'type': null,
            'label': null,
            'inGroupOrder': 6,
            'parentId': null,
            'count': null,
            'functions': null,
            'functionLabel': null,
            'fid': '256'
          },
          {
            'id': '568',
            'isGroup': 0,
            'defaultFunction': null,
            'name': '违规经营',
            'fullName': null,
            'enName': null,
            'icon': null,
            'image': null,
            'url': '/esg/governance/ag/210',
            'status': 0,
            'nextGroupId': null,
            'type': null,
            'label': null,
            'inGroupOrder': 7,
            'parentId': null,
            'count': null,
            'functions': null,
            'functionLabel': null,
            'fid': '257'
          },
          {
            'id': '569',
            'isGroup': 0,
            'defaultFunction': null,
            'name': '反贪污',
            'fullName': null,
            'enName': null,
            'icon': null,
            'image': null,
            'url': '/esg/governance/ag/220',
            'status': 0,
            'nextGroupId': null,
            'type': null,
            'label': null,
            'inGroupOrder': 8,
            'parentId': null,
            'count': null,
            'functions': null,
            'functionLabel': null,
            'fid': '258'
          },
          {
            'id': '570',
            'isGroup': 0,
            'defaultFunction': null,
            'name': '公司党建',
            'fullName': null,
            'enName': null,
            'icon': null,
            'image': null,
            'url': '/esg/governance/ag/230',
            'status': 0,
            'nextGroupId': null,
            'type': null,
            'label': null,
            'inGroupOrder': 9,
            'parentId': null,
            'count': null,
            'functions': null,
            'functionLabel': null,
            'fid': '259'
          },
          {
            'id': '571',
            'isGroup': 0,
            'defaultFunction': null,
            'name': '股东回报',
            'fullName': null,
            'enName': null,
            'icon': null,
            'image': null,
            'url': '/esg/governance/ag/240',
            'status': 0,
            'nextGroupId': null,
            'type': null,
            'label': null,
            'inGroupOrder': 10,
            'parentId': null,
            'count': null,
            'functions': null,
            'functionLabel': null,
            'fid': '260'
          },
          {
            'id': '572',
            'isGroup': 0,
            'defaultFunction': null,
            'name': '投资者关系',
            'fullName': null,
            'enName': null,
            'icon': null,
            'image': null,
            'url': '/esg/governance/ag/250',
            'status': 0,
            'nextGroupId': null,
            'type': null,
            'label': null,
            'inGroupOrder': 11,
            'parentId': null,
            'count': null,
            'functions': null,
            'functionLabel': null,
            'fid': '261'
          }
        ],
        'functionLabel': null,
        'fid': null
      },
      {
        'id': '2005',
        'isGroup': 1,
        'defaultFunction': null,
        'name': '行业对比',

        'functions': [
          {
            'id': '573',
            'isGroup': 0,
            'defaultFunction': null,
            'name': '火电行业',
            'fullName': null,
            'enName': null,
            'icon': null,
            'image': null,
            'url': '/esg/industry/ag/3',
            'status': 0,
            'nextGroupId': null,
            'type': null,
            'label': null,
            'inGroupOrder': 1,
            'parentId': null,
            'count': null,
            'functions': null,
            'functionLabel': null,
            'fid': '236'
          },
          {
            'id': '574',
            'isGroup': 0,
            'defaultFunction': null,
            'name': '钢铁行业',
            'fullName': null,
            'enName': null,
            'icon': null,
            'image': null,
            'url': '/esg/industry/ag/4',
            'status': 0,
            'nextGroupId': null,
            'type': null,
            'label': null,
            'inGroupOrder': 2,
            'parentId': null,
            'count': null,
            'functions': null,
            'functionLabel': null,
            'fid': '237'
          },
          {
            'id': '575',
            'isGroup': 0,
            'defaultFunction': null,
            'name': '水泥行业',
            'fullName': null,
            'enName': null,
            'icon': null,
            'image': null,
            'url': '/esg/industry/ag/5',
            'status': 0,
            'nextGroupId': null,
            'type': null,
            'label': null,
            'inGroupOrder': 3,
            'parentId': null,
            'count': null,
            'functions': null,
            'functionLabel': null,
            'fid': '238'
          }
        ],
        'functionLabel': null,
        'fid': null
      }
    ]
  },
  {
    type: MenuTypeEnum.TILE,
    'id': '30',
    'isGroup': 1,
    'name': '环境与气候',
    'functions': [
      {
        'id': '3001',
        'isGroup': 1,
        'defaultFunction': '464',
        'name': '环境信用',
        'functions': [
          {
            'id': '464',
            'isGroup': 0,
            'defaultFunction': null,
            'name': '环保处罚',
            'fullName': null,
            'enName': null,
            'icon': null,
            'image': null,
            'url': '/environmentCredit/environmentPenalties',
            'status': 0,
            'nextGroupId': null,
            'type': null,
            'label': null,
            'inGroupOrder': 1,
            'parentId': null,
            'count': null,
            'functions': null,
            'functionLabel': {
              'id': null,
              'name': 'HOT',
              'description': null,
              'color': '#F64C4C',
              'bgColor': '#FEEDED'
            },
            'fid': '222'
          },
          {
            'id': '465',
            'isGroup': 0,
            'defaultFunction': null,
            'name': '环保黑名单',
            'fullName': null,
            'enName': null,
            'icon': null,
            'image': null,
            'url': '/environmentCredit/environmentBlackList',
            'status': 0,
            'nextGroupId': null,
            'type': null,
            'label': null,
            'inGroupOrder': 2,
            'parentId': null,
            'count': null,
            'functions': null,
            'functionLabel': null,
            'fid': '223'
          },
          {
            'id': '466',
            'isGroup': 0,
            'defaultFunction': null,
            'name': '环境信用评价',
            'fullName': null,
            'enName': null,
            'icon': null,
            'image': null,
            'url': '/environmentCredit/environmentCreditRate',
            'status': 0,
            'nextGroupId': null,
            'type': null,
            'label': null,
            'inGroupOrder': 3,
            'parentId': null,
            'count': null,
            'functions': null,
            'functionLabel': null,
            'fid': '224'
          }
        ],
        'functionLabel': null,
        'fid': null
      },
      {
        'id': '3002',
        'isGroup': 1,
        'defaultFunction': '538',
        'name': '环境影响评价',

        'functions': [
          {
            'id': '538',
            'isGroup': 0,
            'defaultFunction': null,
            'name': '环评编制信息',
            'fullName': null,
            'enName': null,
            'icon': null,
            'image': null,
            'url': null,
            'status': 1,
            'nextGroupId': null,
            'type': null,
            'label': null,
            'inGroupOrder': 1,
            'parentId': null,
            'count': null,
            'functions': null,
            'functionLabel': {
              'id': null,
              'name': '待上线',
              'description': null,
              'color': '#8B8C8C',
              'bgColor': '#F6F6F6'
            },
            'fid': '324'
          },
          {
            'id': '539',
            'isGroup': 0,
            'defaultFunction': null,
            'name': '备案登记',
            'fullName': null,
            'enName': 'null',
            'icon': null,
            'image': null,
            'url': null,
            'status': 1,
            'nextGroupId': null,
            'type': null,
            'label': null,
            'inGroupOrder': 2,
            'parentId': null,
            'count': null,
            'functions': null,
            'functionLabel': {
              'id': null,
              'name': '待上线',
              'description': null,
              'color': '#8B8C8C',
              'bgColor': '#F6F6F6'
            },
            'fid': '323'
          },
          {
            'id': '540',
            'isGroup': 0,
            'defaultFunction': null,
            'name': '环评受理',
            'fullName': null,
            'enName': 'null',
            'icon': null,
            'image': null,
            'url': null,
            'status': 1,
            'nextGroupId': null,
            'type': null,
            'label': null,
            'inGroupOrder': 3,
            'parentId': null,
            'count': null,
            'functions': null,
            'functionLabel': {
              'id': null,
              'name': '待上线',
              'description': null,
              'color': '#8B8C8C',
              'bgColor': '#F6F6F6'
            },
            'fid': '325'
          },
          {
            'id': '541',
            'isGroup': 0,
            'defaultFunction': null,
            'name': '环评拟审批',
            'fullName': null,
            'enName': 'null',
            'icon': null,
            'image': null,
            'url': null,
            'status': 1,
            'nextGroupId': null,
            'type': null,
            'label': null,
            'inGroupOrder': 4,
            'parentId': null,
            'count': null,
            'functions': null,
            'functionLabel': {
              'id': null,
              'name': '待上线',
              'description': null,
              'color': '#8B8C8C',
              'bgColor': '#F6F6F6'
            },
            'fid': '326'
          },
          {
            'id': '542',
            'isGroup': 0,
            'defaultFunction': null,
            'name': '环评审批',
            'fullName': null,
            'enName': 'null',
            'icon': null,
            'image': null,
            'url': null,
            'status': 1,
            'nextGroupId': null,
            'type': null,
            'label': null,
            'inGroupOrder': 5,
            'parentId': null,
            'count': null,
            'functions': null,
            'functionLabel': {
              'id': null,
              'name': '待上线',
              'description': null,
              'color': '#8B8C8C',
              'bgColor': '#F6F6F6'
            },
            'fid': '327'
          },
          {
            'id': '543',
            'isGroup': 0,
            'defaultFunction': null,
            'name': '环评验收',
            'fullName': null,
            'enName': 'null',
            'icon': null,
            'image': null,
            'url': null,
            'status': 1,
            'nextGroupId': null,
            'type': null,
            'label': null,
            'inGroupOrder': 6,
            'parentId': null,
            'count': null,
            'functions': null,
            'functionLabel': {
              'id': null,
              'name': '待上线',
              'description': null,
              'color': '#8B8C8C',
              'bgColor': '#F6F6F6'
            },
            'fid': '328'
          }
        ],
        'functionLabel': null,
        'fid': null
      },
      {
        'id': '3003',
        'isGroup': 1,
        'defaultFunction': '456',
        'name': '排污许可',

        'functions': [
          {
            'id': '456',
            'isGroup': 0,
            'defaultFunction': null,
            'name': '排污许可信息',
            'fullName': null,
            'enName': null,
            'icon': null,
            'image': null,
            'url': '/sewage/sewagePermit',
            'status': 0,
            'nextGroupId': null,
            'type': null,
            'label': null,
            'inGroupOrder': 1,
            'parentId': null,
            'count': null,
            'functions': null,
            'functionLabel': null,
            'fid': '219'
          },
          {
            'id': '457',
            'isGroup': 0,
            'defaultFunction': null,
            'name': '排污登记信息',
            'fullName': '排污登记信息',
            'enName': null,
            'icon': 'https://hbt.obs.cn-east-2.myhuaweicloud.com/test/app_home_config/2022/05/30/9f022431cab442fda7127a7dccb33654.png',
            'image': null,
            'url': '/sewage/sewageRegister',
            'status': 0,
            'nextGroupId': null,
            'type': 'toWeb',
            'label': null,
            'inGroupOrder': 2,
            'parentId': null,
            'count': null,
            'functions': null,
            'functionLabel': null,
            'fid': '83'
          },
          {
            'id': '458',
            'isGroup': 0,
            'defaultFunction': null,
            'name': '排污申请公开',
            'fullName': null,
            'enName': null,
            'icon': null,
            'image': null,
            'url': '/sewage/sewagePermitBeforeApply',
            'status': 0,
            'nextGroupId': null,
            'type': null,
            'label': null,
            'inGroupOrder': 3,
            'parentId': null,
            'count': null,
            'functions': null,
            'functionLabel': null,
            'fid': '220'
          },
          {
            'id': '459',
            'isGroup': 0,
            'defaultFunction': null,
            'name': '排污限期整改',
            'fullName': '排污限期整改',
            'enName': null,
            'icon': 'https://hbt.obs.cn-east-2.myhuaweicloud.com/test/app_home_config/2022/05/30/3700be9231464434a8e3306f788ec172.png',
            'image': null,
            'url': '/sewage/sewageRectification',
            'status': 0,
            'nextGroupId': null,
            'type': 'toWeb',
            'label': null,
            'inGroupOrder': 4,
            'parentId': null,
            'count': null,
            'functions': null,
            'functionLabel': null,
            'fid': '84'
          },
          {
            'id': '460',
            'isGroup': 0,
            'defaultFunction': null,
            'name': '许可证注销',
            'fullName': '许可证注销',
            'enName': null,
            'icon': null,
            'image': null,
            'url': '/sewage/sewageCancellation',
            'status': 0,
            'nextGroupId': null,
            'type': null,
            'label': null,
            'inGroupOrder': 5,
            'parentId': null,
            'count': null,
            'functions': null,
            'functionLabel': null,
            'fid': '229'
          },
          {
            'id': '461',
            'isGroup': 0,
            'defaultFunction': null,
            'name': '许可证撤销',
            'fullName': null,
            'enName': null,
            'icon': null,
            'image': null,
            'url': '/sewage/sewageRevoke',
            'status': 0,
            'nextGroupId': null,
            'type': null,
            'label': null,
            'inGroupOrder': 6,
            'parentId': null,
            'count': null,
            'functions': null,
            'functionLabel': null,
            'fid': '228'
          },
          {
            'id': '462',
            'isGroup': 0,
            'defaultFunction': null,
            'name': '许可证遗失',
            'fullName': '许可证遗失',
            'enName': null,
            'icon': null,
            'image': null,
            'url': '/sewage/sewageLoss',
            'status': 0,
            'nextGroupId': null,
            'type': null,
            'label': null,
            'inGroupOrder': 7,
            'parentId': null,
            'count': null,
            'functions': null,
            'functionLabel': null,
            'fid': '230'
          },
          {
            'id': '463',
            'isGroup': 0,
            'defaultFunction': null,
            'name': '排污执行报告',
            'fullName': '排污执行报告',
            'enName': null,
            'icon': 'https://hbt.obs.cn-east-2.myhuaweicloud.com/test/app_home_config/2022/05/30/ba8675f673304a5ebdb37c2134a01ac4.png',
            'image': null,
            'url': '/sewage/sewageImplementationReport',
            'status': 0,
            'nextGroupId': null,
            'type': 'toWeb',
            'label': null,
            'inGroupOrder': 8,
            'parentId': null,
            'count': null,
            'functions': null,
            'functionLabel': null,
            'fid': '85'
          }
        ],
        'functionLabel': null,
        'fid': null
      },
      {
        'id': '3004',
        'isGroup': 1,
        'defaultFunction': '472',
        'name': '环境资质',

        'functions': [
          {
            'id': '472',
            'isGroup': 0,
            'defaultFunction': null,
            'name': '危险废物经营许可证',
            'fullName': '危险废物经营许可证',
            'enName': null,
            'icon': 'https://hbt.obs.cn-east-2.myhuaweicloud.com/uat/app_home_config/2022/08/01/05bcae478b5348a6ac946df791afef84.png',
            'image': null,
            'url': '/environmental/operatingPermit',
            'status': 0,
            'nextGroupId': null,
            'type': null,
            'label': null,
            'inGroupOrder': 1,
            'parentId': null,
            'count': null,
            'functions': null,
            'functionLabel': null,
            'fid': '93'
          },
          {
            'id': '473',
            'isGroup': 0,
            'defaultFunction': null,
            'name': '环保工程专业承包资质',
            'fullName': '环保工程专业承包资质',
            'enName': null,
            'icon': 'https://hbt.obs.cn-east-2.myhuaweicloud.com/uat/app_home_config/2022/08/01/ab95c9bfb8e74cfaa5817296e4777a7d.png',
            'image': null,
            'url': '/environmental/professionalContracting',
            'status': 0,
            'nextGroupId': null,
            'type': null,
            'label': null,
            'inGroupOrder': 2,
            'parentId': null,
            'count': null,
            'functions': null,
            'functionLabel': null,
            'fid': '95'
          },
          {
            'id': '474',
            'isGroup': 0,
            'defaultFunction': null,
            'name': '废弃电子产品处理资格',
            'fullName': '废弃电子产品处理资格',
            'enName': null,
            'icon': 'https://hbt.obs.cn-east-2.myhuaweicloud.com/uat/app_home_config/2022/08/01/989ac753ba95464a8b641106966a8fc8.png',
            'image': null,
            'url': '/environmental/wasteElectronicRecycling',
            'status': 0,
            'nextGroupId': null,
            'type': null,
            'label': null,
            'inGroupOrder': 3,
            'parentId': null,
            'count': null,
            'functions': null,
            'functionLabel': null,
            'fid': '96'
          },
          {
            'id': '475',
            'isGroup': 0,
            'defaultFunction': null,
            'name': '辐射安全许可证',
            'fullName': '辐射安全许可证',
            'enName': null,
            'icon': 'https://hbt.obs.cn-east-2.myhuaweicloud.com/uat/app_home_config/2022/08/01/7e51e2438ab54283a433edecc45d8188.png',
            'image': null,
            'url': '/environmental/radiationPermit',
            'status': 0,
            'nextGroupId': null,
            'type': null,
            'label': null,
            'inGroupOrder': 4,
            'parentId': null,
            'count': null,
            'functions': null,
            'functionLabel': null,
            'fid': '94'
          }
        ],
        'functionLabel': null,
        'fid': null
      },
      {
        'id': '3005',
        'isGroup': 1,
        'defaultFunction': '476',
        'name': '重点监控单位',

        'functions': [
          {
            'id': '476',
            'isGroup': 0,
            'defaultFunction': null,
            'name': '清洁生产审核企业',
            'fullName': '清洁生产审核企业',
            'enName': null,
            'icon': 'https://hbt.obs.cn-east-2.myhuaweicloud.com/test/app_home_config/2022/05/30/1961ed8f452645ac8ade521d5836ec67.png',
            'image': null,
            'url': '/keyMonitor/cleanerProduction',
            'status': 0,
            'nextGroupId': null,
            'type': 'toWeb',
            'label': null,
            'inGroupOrder': 1,
            'parentId': null,
            'count': null,
            'functions': null,
            'functionLabel': null,
            'fid': '74'
          },
          {
            'id': '477',
            'isGroup': 0,
            'defaultFunction': null,
            'name': '重点排污单位',
            'fullName': '重点排污单位',
            'enName': null,
            'icon': 'https://hbt.obs.cn-east-2.myhuaweicloud.com/test/app_home_config/2022/05/30/9ee4f747e23e4e3c83fc16f9d0a5602e.png',
            'image': null,
            'url': '/keyMonitor/keySewage',
            'status': 0,
            'nextGroupId': null,
            'type': 'toWeb',
            'label': null,
            'inGroupOrder': 2,
            'parentId': null,
            'count': null,
            'functions': null,
            'functionLabel': null,
            'fid': '76'
          },
          {
            'id': '478',
            'isGroup': 0,
            'defaultFunction': null,
            'name': '重点用能单位',
            'fullName': '重点用能单位',
            'enName': null,
            'icon': 'https://hbt.obs.cn-east-2.myhuaweicloud.com/test/app_home_config/2022/05/30/7a7981a8c82d4e50875b2fb89593071b.png',
            'image': null,
            'url': '/keyMonitor/majorEnergyUsers',
            'status': 0,
            'nextGroupId': null,
            'type': 'toWeb',
            'label': null,
            'inGroupOrder': 3,
            'parentId': null,
            'count': null,
            'functions': null,
            'functionLabel': null,
            'fid': '86'
          }
        ],
        'functionLabel': null,
        'fid': null
      },
      {
        'id': '3006',
        'isGroup': 1,
        'defaultFunction': '470',
        'name': '气候变化',

        'functions': [
          {
            'id': '300601',
            'isGroup': 0,
            'defaultFunction': null,
            'name': '上市公司碳排放',
            'fullName': null,
            'enName': null,
            'icon': null,
            'image': null,
            'url': '/environmentWeather/carbonEmission/ag',
            'status': 0,
            'nextGroupId': null,
            'type': null,
            'label': null,
            'inGroupOrder': null,
            'parentId': null,
            'count': null,
            'functions': null,
            'functionLabel': null,
            'fid': null
          },
          {
            'id': '467',
            'isGroup': 0,
            'defaultFunction': null,
            'name': '碳配额管理单位',
            'fullName': null,
            'enName': null,
            'icon': null,
            'image': null,
            'url': '/environmentWeather/carbonQuota',
            'status': 0,
            'nextGroupId': null,
            'type': null,
            'label': null,
            'inGroupOrder': 4,
            'parentId': null,
            'count': null,
            'functions': null,
            'functionLabel': null,
            'fid': '226'
          },
          {
            'id': '468',
            'isGroup': 0,
            'defaultFunction': null,
            'name': '全国碳履约',
            'fullName': null,
            'enName': null,
            'icon': null,
            'image': null,
            'url': '/environmentWeather/carbonCompliance',
            'status': 0,
            'nextGroupId': null,
            'type': null,
            'label': null,
            'inGroupOrder': 5,
            'parentId': null,
            'count': null,
            'functions': null,
            'functionLabel': {
              'id': null,
              'name': 'HOT',
              'description': null,
              'color': '#F64C4C',
              'bgColor': '#FEEDED'
            },
            'fid': '227'
          },
          {
            'id': '469',
            'isGroup': 0,
            'defaultFunction': null,
            'name': '碳减排支持工具',
            'fullName': null,
            'enName': null,
            'icon': null,
            'image': null,
            'url': '/environmentWeather/carbonReduction',
            'status': 0,
            'nextGroupId': null,
            'type': null,
            'label': null,
            'inGroupOrder': 6,
            'parentId': null,
            'count': null,
            'functions': null,
            'functionLabel': null,
            'fid': '106'
          }
        ],
        'functionLabel': null,
        'fid': null
      }
    ]
  },
  {
    'id': '479',
    'isGroup': 0,
    'name': '资讯',
    'url': '/news/index',
    'fid': '234'
  },
  {
    'id': '480',
    'isGroup': 0,
    'name': '监控',
    'url': '/monitor/index',
    'status': 0,
    'inGroupOrder': 2,
    'fid': '273'
  },
  {
    'id': '422281',
    'isGroup': 0,
    'name': 'App',
    'url': '/monitor/index',
    'status': 0,
    render: <div class="content-main app-content-main">
      <div class="desc">
        <div class="title">蔚蓝之星</div>
        <div class="intro">专业智能数据</div>
        <img class="qrCode" src="./assets/logo.png" width="108" height="108"/>
        <div class="text">扫码立即下载APP</div>
      </div>
      <div class="phone-img">
      </div>
    </div>,
    subMenuCfg: {
      toolTipCfg: {
        showArrow: true
      }
    }
  }
];

recursion(headerList, (item => {
  if (item?.functions?.length) {
    item.disabled = false;
  } else {
    item.disabled = !item.url;
  }
}), 'functions');

const menuStyle = generateCssVars({
  'text-color': 'white',
  'hover-bg-color': 'white',
  'focus-bg-color': 'white',
  'active-color': 'white',
  'item-min-width': '150px',
  'border-bottom': 'none',
  'item-border-bottom': 'none',
  'item-active-border-bottom': 'none'
}, 'menu');
</script>

<template>
  <div class="header-menu h-40px bg-#15B4F1 flex align-center" :style="{...menuStyle,
   '--vft-popper-border-radius': '10px'}">
    <vft-horizontal-menu :menus="headerList" openDisabled useTileMenuTransition
      :subMenuCfg="{expandIcon: 'ico-ic:outline-arrow-drop-down', collapseIcon: 'ico-ic:outline-arrow-right'}"
      :attrMapping="{title: 'name', children: 'functions'}">
      <template #menuItem="{item}">
        <span :class="['item-con']">
          <span class="vft-menu-item__text">{{ item.fullName || item.name }}</span>

          <link-status
            v-if="item?.functionLabel"
            :color="item?.functionLabel?.color"
            :bgColor="item?.functionLabel?.bgColor"
            :name="item?.functionLabel?.name"
          />
        </span>
      </template>
    </vft-horizontal-menu>
  </div>

</template>

<style lang="scss" scoped>
.header-menu {
  :deep(.vft-horizontal-menu) {
    .vft-sub-menu__text {
      padding-right: 5px;
    }

    .vft-menu-popup-item:not(.is-disabled) {
      color: black;
      &:hover{
        color: $primary-color;
      }
    }
    .vft-menu-popup-item {
      color: black;
    }

    .vft-sub-menu__0 {
      .vft-sub-menu__text{
        font-size: 16px;
      }
    }

    .vft-menu-item-first {
      .vft-menu-item__text {
        font-size: 16px;
      }
    }

    .vft-sub-menu__0.is-opened {
      background-color: white;
      .vft-sub-menu__title {
        color: $primary-color!important;
      }
    }

    .vft-menu-popup-item * {
      vertical-align: middle;
    }
  }
}
</style>
