const list = [
  ['MDN', 'https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Object/toString'],
  ['阮一峰ES6教学', 'https://es6.ruanyifeng.com/#docs/module'],
  ['阮一峰ES5教学', 'https://wangdoc.com/javascript/'],
  ['eslint官方地址', 'https://eslint.bootcss.com/'],
  ['Eslint中文开发手册', 'https://cloud.tencent.com/developer/section/1135613'],
  ['hammer.js中文文档', 'https://www.cnblogs.com/qianduanjingying/p/5812139.html'],
  ['TinyMCE中文文档', 'http://tinymce.ax-z.cn/'],
  ['BootCDN', 'https://www.bootcdn.cn/'],
  ['维基百科', 'https://zh.wikipedia.org/wiki/%E6%8A%BD%E8%B1%A1%E8%AA%9E%E6%B3%95%E6%A8%B9'],
  ['stylelint', 'http://stylelint.docschina.org/user-guide/rules/'],
  ['stylelint-1', 'http://stylelint.cn/user-guide/'],
  ['dplayer', 'https://dplayer.diygod.dev/'],
  ['Day.js中文网', 'https://dayjs.fenxianglu.cn/category/'],
  ['chrome调试技巧', 'https://www.frontendwingman.com/'],
  ['技术开发分享导航站', 'https://www.fenxianglu.cn//'],
  ['现代 JavaScript 教程', 'https://zh.javascript.info//'],
  ['husky', 'https://typicode.github.io/husky/#/?id=migrate-from-v4-to-v6'],
  ['rollup中文', 'https://www.rollupjs.com/guide/tutorial'],
  ['rollup文档', 'https://rollupjs.org/'],
  ['husky使用总结', 'https://zhuanlan.zhihu.com/p/366786798'],
  ['前端开发者需要知道的 package.json', 'https://juejin.cn/post/6969454249411837965'],
  ['inquirer.js', 'https://blog.csdn.net/qq_26733915/article/details/80461257'],
  ['purgecss中文文档', 'https://www.purgecss.cn/'],
  ['axios中文网', 'http://www.axios-js.com/'],
  ['lottie-web', 'https://www.yuque.com/lottie/document/web'],
  ['UglifyJS中文文档', 'https://segmentfault.com/a/1190000008995453'],
  ['gulpjs', 'https://www.gulpjs.com.cn/docs/api/task/'],
  ['Prettier 中文网', 'https://www.prettier.cn/docs/index.html'],
  ['AST编译转换', 'https://astexplorer.net/'],
  ['mongodb', 'https://www.mongodb.org.cn/'],
  ['netlify', 'https://app.netlify.com/teams/miofly/overview'],
  ['gitlab', 'https://gitlab.com/Miofly/mio-blog'],
  ['周报生成器', 'https://weeklyreport.avemaria.fun/zh']
];

export default {
  category: '技术文档地址',
  order: 1,
  list
};
