const list = [
  ['CSDN', 'https://blog.csdn.net/weixin_40013817'],
  ['掘金', 'https://juejin.cn/frontend'],
  ['简书', 'https://www.jianshu.com/'],
  ['博客园', 'https://www.cnblogs.com/'],
  ['思否', 'https://segmentfault.com/'],
  ['美团技术团队', 'https://toutiao.io/u/240597?f=new'],
  ['黑客资讯', 'https://hackernews.cc/archives/category/%E9%BB%91%E5%AE%A2%E4%BA%8B%E4%BB%B6'],
  ['infoq', 'https://www.infoq.cn/topic/Front-end'],
  ['牛客网', 'https://www.nowcoder.com/'],
  ['鱼塘', 'https://mo.fish/'],
  ['36氪', 'https://36kr.com/'],
  ['知乎-尤雨溪', 'https://www.zhihu.com/people/evanyou/answers'],
  ['微博-尤雨溪', 'https://weibo.com/arttechdesign'],
  ['v2ex', 'https://www.v2ex.com/?tab=all'],
  ['腾讯云', 'https://cloud.tencent.com/developer/information/'],
  ['开发者头条', 'https://toutiao.io/'],
  ['开源中国', 'https://www.oschina.net/'],
  ['web前端导航', 'http://www.alloyteam.com/nav/'],
  ['theme-hope', 'https://theme-hope.vuejs.press/zh/'],
  ['theme-hope自定义容器', 'https://plugin-md-enhance.vuejs.press/zh/guide/container.html'],
  ['theme-hope案例', 'https://theme-hope.vuejs.press/zh/demo.html'],
  ['vuepress-theme-reco', 'https://vuepress-theme-reco.recoluan.com/'],
  ['博客案例', 'https://www.weigao.cc/?page=2'],
  ['antfu-blog', 'https://antfu.me/posts'],
  ['李伟', 'https://www.leevii.com/page/1'],
  ['openwrite', 'http://admin.openwrite.cn/#/diffusion/article'],
  ['xugaoyi', 'https://xugaoyi.com/pages/dcebaf/'],
  ['如何自动提交站点地图给谷歌', 'https://taixingyiji.com/search/google/sitemap/#%E5%89%8D%E8%A8%80'],
  ['谷歌站点', 'https://search.google.com/search-console?resource_id=https%3A%2F%2Fwflynn.cn%2F&hl=zh-CN'],
  ['Markdown同步微信', 'https://www.wechatsync.com/md/?utm_source=homebtn#/'],
  ['waline', 'https://waline.js.org/guide/get-started/#vercel-%E9%83%A8%E7%BD%B2-%E6%9C%8D%E5%8A%A1%E7%AB%AF'],
  ['leancloud', 'https://console.leancloud.app/apps/Bntkn01CEGDIzypQnPaNGV4B-MdYXbMMI/']
];

export default {
  category: '技术博客网站',
  order: 20,
  list
};
